### ISSUE TITLE
New Term - preparationMethod

### ISSUE THREAD

**Issue by ManonGros** [tdwg/dwc#288] opened 2020-10-02 12:56 UTC
I am simply forwarding an issue from our repo: https://github.com/gbif/portal-feedback/issues/2429
I think it seems like the right place for it but let me know if not, thanks!

> **preparations vs preparationMethod**

> Currently there is in DwC only one field preparations in which all the information about the preservation of a certain object is stored.
As far as I know there is no way to differentiate between how certain objects are preserved (e.g. air dried, 70% alcohol, formalin, etc) and what kind of objects (e.g. skeleton, skin, tissue, whole organism) are preserved. Or am I wrong? For certain data users it might worthwhile to be able to look at the alcohol collection for certain specimens or for exhibition purposes to find all mounted objects of a certain taxon for example.

> Are there any possibilities to make differences between preparations and preparationMethods (as it is called in ABCD)? And/or are there plans to create a field like preparationMethod?

**Comment by tucotuco** [comment] 2020-10-02 13:53
Duplicate of issue #1. Closing here.

**Closed by tucotuco** 2020-10-02 13:53 UTC
