### ISSUE TITLE
Change term - associatedSequences

### ISSUE THREAD

**Issue by deepreef** [tdwg/dwc#348] opened 2021-04-28 06:49 UTC
## Change term

* Submitter: Richard Pyle
* Proponents (who needs this change): Everyone?
* Justification (why is this change necessary?): Genetic sequences are derived from physical material (e.g., tissue samples), which are examples of MaterialSample instances. While the tissues samples from which associated sequences are derived may have been collected or obtained in the context of an Occurrence, the more direct source for associated sequences is the physical material from which the sequences were made.

Proposed new attributes of the term:

* Term name (in lowerCamelCase): associatedSequences
* Organized in Class (e.g. Location, Taxon): MaterialSample
* Definition of the term: A list (concatenated and separated) of identifiers (publication, global unique identifier, URI) of genetic sequence information associated with the MaterialSample.
* Usage comments (recommendations regarding content, etc.): 
* Examples: `http://www.ncbi.nlm.nih.gov/nuccore/U34853.1`, `http://www.ncbi.nlm.nih.gov/nuccore/GU328060` | `http://www.ncbi.nlm.nih.gov/nuccore/AF326093`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/associatedSequences-2017-10-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Sequences/Sequence/ID-in-Database + constant

This proposal is primarily to organize this term within the `MaterialSample` class, rather than the `Occurrence` class. Doing so requires a slight modification to the definition. Discussion around changes to MaterialSample on DwC (#314). There is some uncertainty whether this property is more appropriately organized in the `MaterialSample` class or the `Organism` class.  Both represent potential direct sources of genetic material, but instances of `MaterialSample` are the most direct source (as `MaterialSamples` are derived from `Organisms`).  Alternatively, this term could be deprecated in favor of providing more structured relationships with MaterialSample instances via instances of `ResourceRelationship`. For now, though, it seems most appropriate to reclassify this term within the MaterialSample class.

**Comment by deepreef** [comment] 2021-04-28 06:53
#332

**Comment by tucotuco** [comment] 2021-04-29 00:09
Duplicate of Issue #332. Closing.

**Closed by tucotuco** 2021-04-29 00:09 UTC
Labels: Term - change
