### ISSUE TITLE
New term - organismStatus

### ISSUE THREAD

**Issue by sophiathirza** [tdwg/dwc#228] opened 2019-05-29 10:48 UTC
### This proposal is under active development in the ['OSR - How Did It Die?' Task Group](https://www.tdwg.org/community/osr/how-did-it-die/).

* Submitter: Sophia Ratcliffe - NBN Trust (https://nbnatlas.org/)
* Proponents (at least two independent parties who need this term): I have had requests from several of our data providers asking for the ability to supply and filter records by alive/dead status
* Justification (why is this term necessary?): We receive many records where the occurrence was of a dead animal and at the moment there is no way store the status of the organism in a DwC term with a controlled vocabulary. It is really important in marine records, which often contain stranding information, and for road kill records.

Proposed definition of the new term:

* Term name (in lowerCamelCase): organismStatus
* Class (e.g. Location, Taxon): organism
* Definition of the term: A description of the status of the organism (alive or dead)
* Comment (examples, recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary, with the terms alive, dead, unknown
* Refines (identifier of the broader term this term refines, if applicable): Currently we've been using occurrenceRemarks, but it is not easily searchable.
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): N/A
* ABCD 2.06 (XPATH of the equivalent term in ABCD, if applicable): N/A

**Comment by qgroom** [comment] 2019-05-29 13:26
I support the concept, but not so much the suggested name. Status can mean so many things. Can't think of a better one yet.

Also, there is the issue of dead museum specimens and living culture collections. I'm not certain these matter if they are described as dead or alive, as long as it is appropriate, but it is worth considering. I think basisOfRecord is currently used for some of these distinctions.

**Comment by sophiathirza** [comment] 2019-05-29 13:36
Yes, I didn't like using status, but it felt consistent with other DwC terms. 

The new term would be used for field observations where the basisOfRecord is HumanObservation (or Occurrence, as some data providers use).

**Comment by MattBlissett** [comment] 2019-05-29 14:33
A possible name could use *vitality*.

Or *viability*, which is already used for seed collections (values might be viable, dormant, inviable, dead)

**Comment by qgroom** [comment] 2019-05-29 14:42
I like `vitality`.

**Comment by as6699** [comment] 2019-05-29 16:40
Would reproducing or fertile be appropriate values for this term in that case? It's important for determining if a non-native species is established. (Excuse and ignore if another term already takes this into account.)

Annie Simpson

________________________________

**Comment by qgroom** [comment] 2019-05-29 18:13
>Would reproducing or fertile be appropriate values for this term in that case?

`reproductiveCondition` and `lifeStage` cover this

**Comment by sophiathirza** [comment] 2019-05-30 07:41
I like vitality

**Comment by qgroom** [comment] 2019-05-30 07:59
Could the definition be changed to 

`An indication of whether the organism was alive or dead at the time of collection or observation`.

Comment: Generally Intended to be used with a `dwc:basisOfRecord` of  `PreservedSpecimen`, `MaterialSample`, or `HumanObservation`.

**Comment by qgroom** [comment] 2019-05-30 08:00
A further thought

If this field is added to Darwin Core then next obvious need would be `causeOfDeath`.

Rather than just having a flag to say if something is dead, why not jump straight to a `causeOfDeath` field with a vocabulary?

**Comment by sophiathirza** [comment] 2019-05-30 08:22
causeOfDeath would be really useful, then we can differentiate strandings, road kills etc.

A single term for vitality, with @qgroom's suggestion for the definition and comment, would still be useful, so that we can easily select all 'dead' records, but if needs be, we can derive that from causeOfDeath.

**Comment by qgroom** [comment] 2019-05-30 16:50
I don't like boolean flag fields in the standard when they can be derived from other fields. This doesn't mean they can't be implemented in a database to make searching faster, but as long as they are always derived from one source field there is no danger of a mismatch, where for example one `vitality` says `living`, but the cause of death is `roadkill`.

It is a good question for GBIF though. @MattBlissett was saying `dwc:year` is derived from `dwc:eventdate` if it is empty. How much is GBIF willing to add non-standard fields for indexing if they are derived from standard fields?

**Comment by stanblum** [comment] 2019-05-31 08:09
I would like to urge some caution here. In other words, please be very
explicit about your needs or use-case(s) for a controlled vocabulary
describing whether an organism is/was dead or alive.  In many 'collecting
events", whole organisms are encountered alive, but the process transforms
them to dead.  Organisms can be observed dead or alive in the field.  An
organism could have been collected alive (a long time ago), lived many
years in captivity, and be dead now.   "causeOfDeath" could venture easily
into necropsy results.  In the case of cetacean and pinniped "strandings"
(i.e., organisms encountered dead on the shoreline), the cause of death is
of great interest and represents a summary conclusion based evidence found
in necropsy, pathology, and/or toxicology.

**Comment by MathildeMousset** [comment] 2019-07-04 07:38
Potential user here: we work on wild ungulates, and would be interested in `vitality` and `causeOfDeath` terms. 

Some of our data is road kill data (individual observed dead, with an obvious cause), hunting data (dead animals, through various types of hunting methods), monitoring data (live animals / animals found dead).

**Comment by qgroom** [comment] 2019-07-09 14:40
The executive of TDWG  thinks this is an important issue to consider. The first step would be to engage in discussion with the Darwin Core Maintenance Group to figure out the next steps.

@tucotuco @peterdesmet @mdoering @timrobertson100 @baskaufs @pzermoglio @morr @chicoreus

**Comment by chicoreus** [comment] 2019-07-09 15:14
Consideration by the Darwin Core Maintenance Group should include whether development of this term  and a controlled vocabulary of values for it (including the development of user stories and competency questions) would fall within the scope of the maintenance group, or whether this work is of sufficient scope to merit a new task group.

Consideration also needs to be paid to alignment with ABCD, including the PaleontologicalUnit/Preservation/Taphonomy and PaleontologicalUnit/Preservation/Completeness terms.

**Comment by baskaufs** [comment] 2019-07-12 23:35
It seems to me that this term should be organized under the Occurrence class rather than Organism.  In the thread, we've been talking about the status of the organism at the time when it was observed or collected.  That makes it specific to a particular Occurrence of the organism, since an organism can be observed repeatedly and on some of those Occurrences it might have been alive, then dead on its last occurrence (perhaps being made to be dead by the collection).

**Comment by tucotuco** [comment] 2019-07-13 09:58
@baskaufs Agree. Changed label.

**Comment by mdoering** [comment] 2019-07-31 14:15
I very much like the term `vitality` and we should probably think about a short accompanying vocabulary that is more expressive than just the binary dead or alive. 

Would you also use it for exuviae or shells? 
I found a slide from 2014 about establishmentMeans and its actual content in GBIF which contained a few indications to dead organisms. It seems `causeOfDeath` is a good company for vitality:

<img width="668" alt="Screenshot 2019-07-31 at 16 12 27" src="https://user-images.githubusercontent.com/327505/62219219-3405fd80-b3ae-11e9-80f1-3ea671c53f2f.png">

**Comment by qgroom** [comment] 2019-10-26 13:11
Notes from the Biodiversity Next Unconference 25 October 2019




Vitality=CauseOfDeath

**Introduction**
Linked to the...
- decay process
- health
- taphonomy
- species interactions (disease, pests, predators)

Relates to dwc:basisOfRecord
- PreservedSpecimen
- FossilSpecimen
- HumanObservation
- LivingSpecimen

**Use Cases**
- Disease Ecology
- Causes of death in a living collection (animals and plants)
- Historical studies
- The last specimen of an extinct taxon
- Understanding the genomics of dead organisms (e.g. non-target organisms)
- Communication with the public about the origins of collections
- identifying roadkill hotspots
- Documenting whale strandings
- Studying the phenology of death
- Quantifying by-catch in invasive species control programs
- Reducing unnecessary mortality of endangered species.

**Scope**
- When did it die? (also see dwc:GeologicalContext)
- Collection methods (dwc:samplingProtocol)
- Should close to death be included?
-  Uncertainty
- "Natural" versus "unnatural" death
- Multiple causes of death e.g. killed on road as a cause of blindness caused by disease.

Consider the public sensitivity towards death and killing animals.

**Team 1:**
1. Collected Dead
- "Natural Causes"
- Predation
- Storms/weather
- Disease
- Age/Senescence

(Fossils: Location)
+Confidence level of above

2. Killed when collecting
- Pitfalls
- Biobanks: alive?
- Trapped
- Shot
- Picked
- Harvested

3. Cause of death ambiguous
Further data needed
Unsure at time of collecting

**Team 2:**
#causeOfDeath
- trapped
- poisoned
- starved
- drowned
- shot
- of old age
- road kill
- disease
- weeding
- collecting
- burned

Direct cause of death linked to event in time, such as a volcano eruption
Are there pathology ontologies?

**Team 3:**
SALAFSKY, N. , SALZER, D. , STATTERSFIELD, A. J., HILTON‐TAYLOR, C. , NEUGARTEN, R. , BUTCHART, S. H., COLLEN, B. , COX, N. , MASTER, L. L., O'CONNOR, S. and WILKIE, D. (2008), A Standard Lexicon for Biodiversity Conservation: Unified Classifications of Threats and Actions. Conservation Biology, 22: 897-911. doi:10.1111/j.1523-1739.2008.00937.x

- Experimental [death]
- Anthropogenic [death]
- Biotic/Abiotic [death]
- Environmental [death]

- Serves as marker/flag for follow-up in downstream uses
- medical concepts/terms might already exist
- 10-20 Use cases to test against

Age at death?
Would it have died anyway?
Whose fault is it?
Collection event

**Team 4:**
Cause and qualifier
When?

![IMG_20191026_123528951](https://user-images.githubusercontent.com/5530576/67620022-bdd53380-f802-11e9-9695-4f1356547369.jpg)
![IMG_20191026_123541129](https://user-images.githubusercontent.com/5530576/67620024-bdd53380-f802-11e9-9a60-c564e68b9370.jpg)
![IMG_20191026_123521290](https://user-images.githubusercontent.com/5530576/67620025-bdd53380-f802-11e9-8135-a17160932cca.jpg)

**Comment by qgroom** [comment] 2019-10-26 17:03
Codes used to express plant losses at Meise Botanic Garden

DIE_WHY_CODES	DIE_WHY_CODES	DESCRIPTION
D	D	discarded
ES	ES	environmental stress (cold, heat, drought)
FR	FR	failed to root
H	H	horticultural failure
N	N	neglect / error
ND	ND	natural disaster (hurricane, flood, etc.)
P	P	pest
R	R	re-accessioned under a new name
RF	RF	rootstock failure
SO	SO	sold
V	V	made into a voucher specimen
NV	NV	no viable seed
X	X	not coded
ANS	ANS	annual - seeds saved but original plants discarded
ANU	ANU	annual - died after flowering, no viable seed produced
A	A	animal damage
DI	DI	disease
FG	FG	failed to germinate
G	G	given away
NC	NC	natural cause (old age, etc.)
O	O	other
S	S	stolen
U	U	unable to locate
W	W	weeds / competition
VA	VA	vandalism
SH	SH	shaded out / overgrown
WT	WT	changes to water table

**Comment by OBISCanada** [comment] 2019-11-11 12:12
Is it still possible to contribute to this conversation related to OccurrenceStatus. Currently there are 2 terms: present or absent.  if an animal/plant is dead it is still present.  I would like to propose the addition of a new term called 'trace'. This term could be assigned to observations of shells - these animals should not be flagged as present/dead if the shell is empty.  a crab shell can be considered present/dead but an empty snail shell should be flagged as 'trace'. 
Other cases where 'trace' could be assigned are when one observes scat, tracks, nests, etc. In these cases there are 'traces' that an animal was present at this location at some time in the past. the animal is not present at the time that the observation was made. It does not imply that the animal is dead.

**Comment by qgroom** [comment] 2019-11-17 07:00
Many different things are added to the Darwin Core field establishmentMeans and published on GBIF.
This file contains a list of the terms relating to death that have been put in establishmentMeans.
[DeadEntriesPutInEstablishmentMeans.xlsx](https://github.com/tdwg/dwc/files/3855308/DeadEntriesPutInEstablishmentMeans.xlsx)

**Comment by qgroom** [comment] 2019-11-22 07:35
Causes of Death from the UK Predatory Bird Monitoring Scheme (PBMS)
From  Lee A. Walker of the UK's Centre of Ecology and Hydrology.

BOP_USER_BOP_COD_DESC |   |  
-- | -- | --
COD_ID | COD_DESC | COD_ABRIDGED
2 | Window collision | Accident
3 | Shot | Shot and Special   Collection
4 | Collision | Accident
5 | Starvation   through injury | Accident
6 | Unknown Trauma | Unknown
7 | Disease | Starvation and   Disease
8 | Other trauma | Accident
9 | Starvation | Starvation and   Disease
10 | Poison | Poison
11 | Road accident | Accident
12 | Human predation | Accident
13 | Animal predation | Accident
14 | Drowning | Accident
15 | Experimental   collection/Euthenasia | Shot and Special   Collection
16 | Electrocution | Accident
1 | Unknown | Unknown
  |   |  

Email from Lee states

> Although the CoD list is in our standard operating procedures these are not citable. However the list is published in the supporting documentation for a dataset that we have published in the UK EIDC data catalogue.

> The record is here: https://catalogue.ceh.ac.uk/documents/e39e3afb-eb90-4a7d-921d-e03b1a0f414d

 

> The specific file can be accessed through the link below which downloads a zip file. The CoD list is in the column_headings_predatory_bird_livers.csv file.

> https://data-package.ceh.ac.uk/sd/e39e3afb-eb90-4a7d-921d-e03b1a0f414d.zip

**Comment by albenson-usgs** [comment] 2020-04-15 19:22
Curious if this has advanced since 2019? I have a dataset of dead marine mammals and seabirds that wash up on shore and I haven't heard a new term has been added.

**Comment by sophiathirza** [comment] 2020-04-15 21:42
It hasn't progressed further than agreeing to set up a task group to explain the rationale of adding new terms for vitality and cause of death and their vocabularies.  I've started the charter and meant to send it round to very one for comment. Let me know if you're interested in being involved. Thanks.

**Comment by qgroom** [comment] 2020-04-16 07:54
@sophiathirza I'm still keen to make progress on this. Let me know if there is anything I can do.
@albenson-usgs It would be useful to know what terms you want to use for your standings dataset.

**Comment by OBISCanada** [comment] 2020-04-16 11:57
Yes please include me!
Thanks
Mary Kennedy

Sent from Mail for Windows 10

**Comment by albenson-usgs** [comment] 2020-04-16 13:18
@qgroom I believe if I'm reading this thread correctly that I would want to use vitality. I'm not sure about causeOfDeath- I haven't seen the dataset yet to know if that's in there.

**Comment by JohnNichollsTCD** [comment] 2020-05-15 11:33
When will a resolution be made on this matter? It appears that a great deal of valuable energy and thought has gone into it, so are we at a stage where a decision can be made? I have a colleague who is eager to submit data into OBIS but needs to have this clarified to ensure his work is interpreted correctly.

**Comment by OBISCanada** [comment] 2020-05-15 11:41
Also curious if there are plans to address the question about 'evidence' when one doesn't know if dead or alive?  in the case of shells maybe one can assume dead but maybe the organism did not die at that location. evidence might be of more interest to terrestrial critters - tracks, faeces, nests, molts, etc.

**Comment by JohnNichollsTCD** [comment] 2020-05-15 12:13
Totally valid point - fortunately in my case, it literally is looking at shells, so not an issue for me.

**Comment by qgroom** [comment] 2020-05-16 05:50
It is great to see so much interest in these terms!

Here are my thoughts...

- In order for this to become part of the ratified standard it requires someone to convene a task group and create a proposal. This can be a team of people.
- Use of the term `vitality` appears uncontroversial and if people start using it as a pilot then this would only reinforce the evidence that it is needed.
- It would have terms `alive`, `dead`, `unknown`
- We already have a proposed definition...
> An indication of whether the organism was alive or dead at the time of collection or observation
- It could use more explanation of its uses. For example, for collection methods that result in the death of the organism and are there any advise for cases such as fossils, shells and animal tracks and signs.
- `causeOfDeath` needs more work (but not much). A good start would be to collated all the causes of death listed in this thread into one vocabulary, then pilot this in some of your systems.
- Expressing the evidence for knowing something is dead of alive has not yet been tackled. Indeed, there are few means to express this in Darwin Core for other terms. I suggest that this a tertiary consideration for now.

Please do volunteer for some of this work. There is rarely such a clear case that terms like this are needed.

**Comment by JohnNichollsTCD** [comment] 2020-05-16 10:33
Thank you for your valuable insights and clarity Quentin.

I wish to propose that a Task Team is convened immediately and that the proposal is put to the OBIS Steering Group for consideration as a matter of urgency. A decision needs rot be made as soon as possible.

If I understand this correctly, ratification would need to be actioned via the DwC Darwin Core Task Group.

I propose that we establish the Task Team with immediate effect. Would anyone who champions the inclusion of the term "vitality" with options of alive, dead or unknown, show their interest in joining this TT by responding to this message and enabling us to take it forward.

I hope that this action will lead to a speedy resolution.

John Nicholls
(OBIS EC, OBIS SG, OBIS COTT Chair)




John Nicholls

Data Manager / Researcher
NorFish Project https://www.tcd.ie/history/research/centres/ceh/norfish/people.php
Centre for Environmental Humanities
6th floor, Arts and History Department
Trinity College Dublin
College Green, Dublin 2
Email: john.nicholls@tcd.ie<mailto:cscherer@tcd.ie>
Phone: +3531896-1663

[cid:78903c9e-8289-4cc9-8907-2af01aa66977]

________________________________

**Comment by OBISCanada** [comment] 2020-05-16 11:05
I am interested 
Mary Kennedy
Dartmouth, NS

**Comment by qgroom** [comment] 2020-05-16 11:38
To form a TDWG task Group you need to write a charter, something like this...
[example charter](https://www.tdwg.org/community/attribution/people/). You then submit it to the Executive for acceptance. They are unlikely to reject it, but they often have comments and suggestions.

The task group needs to have an umbrella Interest Group, which I guess would be the [Observations & Specimens Interest Group](https://www.tdwg.org/community/osr/). 

This little bit of bureaucracy will help you later on when it comes to ratification, because you can show your due diligence on communication with the 'community'.

To expedite the process it might be best to separate `vitality` from `causeOfDeath`. I suspect the latter will be more tricky, whereas the former could be proposed in a short paper in [BISS](https://biss.pensoft.net/).

**Comment by sophiathirza** [comment] 2020-05-18 06:58
@qgroom, sorry for my delay writing the charter. I'll finish it off this week and send it round. Thanks, Sophia

**Comment by qgroom** [comment] 2020-05-18 08:55
@sophiathirza that's fantastic! I guess it would be easiest to share it here, but at some point soon we should transition off this issue thread.
Once there is an official task group there can be a TDWG repository for the group to share thoughts and documents.

**Comment by sophiathirza** [comment] 2020-06-15 15:07
The Charter for the new Task Group is attached. Please send me any comments/additions and let me know whether you would like to be added to the list of core members.

I will then submit the final version to TDWG.

Thanks, Sophia

[How did it die - task_group_charter.docx](https://github.com/tdwg/dwc/files/4781129/How.did.it.die.-.task_group_charter.docx)

**Comment by JohnNichollsTCD** [comment] 2020-06-15 15:59
Dear Sophia

Thank you for sending this on. It looks great and fit for purpose.

The only minor observation is that I added my own affiliation (John Nicholls, OBIS, Ireland)

Best wishes

John


John Nicholls

Data Manager / Researcher
NorFish Project https://www.tcd.ie/history/research/centres/ceh/norfish/people.php
Centre for Environmental Humanities
6th floor, Arts and History Department
Trinity College Dublin
College Green, Dublin 2
Email: john.nicholls@tcd.ie<mailto:cscherer@tcd.ie>
Phone: +3531896-1663

[cid:39354813-2db9-4c62-bc6a-a2e9a259a6a8]

________________________________

**Comment by tucotuco** [comment] 2020-06-15 19:40
Thanks for all the interest in these changes. I think the process is
correct, but I believe that the Task Group should be instantiated
under the Darwin
Core Maintenance Group <https://www.tdwg.org/community/dwc/> rather than
the Observations & Specimens Interest Group
<https://www.tdwg.org/community/osr/>. I guess the TDWG Executive needs to
decide that based on the scope of the tasks proposed, but the Darwin Core
Maintenance Group is an Interest Group, and seems to me to have the correct
scope based on the discussion so far.

**Comment by pzermoglio** [comment] 2020-06-15 20:26
@tucotuco I think it would be appropriate that the Task Group be under the Observations & Specimens Interest Group, as @qgroom suggests. I don't think the Darwin Core Maintenance group should be dealing with this. In cases were new terms (or changes to existing terms) are needed that deal with specific necessities of the community, task groups that are specific to those needs should be under interest groups that are also specific (although less so) to those needs. Maybe in this case is not so obvious, but suppose some other case where paleo terms were needed. One should not expect the DwC MG -or task group within it- to deal with building those terms, their definitions, etc., but rather have the expert groups do it, and come to the DwC MG with a solid, full proposal, for incorporation of new/changed terms.
To put it more briefly, I envision experts in expert groups, and the DwC MG in more of a maintenance/overseeing role. Communication between the groups would of course be of capital importance to the whole process. Also, probably the charter should include a particular task to have the terms ratified in Darwin Core.

As for what the [Vocabulary Maintenance Specification](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md) says, it could actually happen both ways:
> 2.1 [...] In the case where a new vocabulary is related to an existing vocabulary having an existing maintaining Interest Group, maintenance of the new vocabulary may be assigned to the existing Interest Group. [...]

> 2.2 The vocabulary maintenance Interest Group may also establish Task Groups to accomplish broader changes to the standard, such as creating or revising associated documents, or determining how the terms of the vocabulary might be used with a new technology.

@baskaufs Thoughts?

**Comment by baskaufs** [comment] 2020-06-16 12:33
My initial thought was that @tucotuco was correct, particularly since the charter describes the creation of two new Darwin Core terms, and that would clearly be the responsibility of the DwC Maintenance Group to shepherd. 

However, upon further reflection, I was thinking about the spirit behind section 4 of the VMS. Section 4 describes the development of "vocabulary enhancements". Vocabulary enhancements are defined in section 1.4 and development of controlled vocabularies does not fall within their definition. But the rationale behind section 4 is that when a set of coordinated additions to a vocabulary become complex, it is best to consider them a package that has a higher standard for development and testing than would be necessary for the adoption of a single term. In that situation, the best practice is to document the rationale and implementation testing through the two types of user feedback reports described in section 4. 

In Audubon Core, we are currently working three coordinated sets of additions to the standard (a set of terms related to 3D, controlled vocabularies for ac:subjectPart and ac:subjectOrientation, and a set of terms related to sound). Two of these sets of additions have associated task groups chartered under the MG and one does not. But given that they are complex coordinated additions, as AC MG convener, I'm requesting a Feature Report and Implementation Experience Report for all three proposals. The point of those reports is to streamline the adoption process by making it clear during the public comment period and Executive Decision what the proposal is supposed to accomplish and that it actually can accomplish what was proposed. 

The last paragraph is somewhat tangential to the question at hand, but the point of section 4 of the VMS is about how to effectively implement changes to a standard that are more complicated than a single term addition. Section 4 specifically allows vocabulary enhancements to be proposed by groups that are NOT task groups chartered by the maintenance group in order to enable those who take initiative and do the work to succeed in improving TDWG vocabularies regardless of whether the maintenance group asked them to do it or not. Given that spirit, if chartering this proposed Task Group under an interest group other than the DwC Maintenance Group is the most effective way to get a good proposal, then I wouldn't oppose that.

The one thing that concerns me a bit about not chartering the Task Group under the Darwin Core MG is wondering how the task group would relate to the Observations and Specimens Group and to the DwC Maintenance Group. The last paragraph of section 4.1 of the VMG describes a back and forth process between the vocabulary MG and the group developing the enhancement, where the MG evaluates how the proposal will fit in with the operation of the existing vocabulary and gives feedback to the TG if it does not think the proposal is ready. The MG essentially acts as the gatekeeper to determine when the proposal is mature enough to advance to public comment. (In this case, the MG is acting in the role that would be assumed by a Review Manager for a new standard.)  I'm assuming that if the Observations and Specimens Group Interest group charters this task group, the DwC MG would still operate in this gatekeeper role and that the O&S group would just act in an advisory role for the development of a better proposal. But I think it would be good to be clear about this from the start since we would be potentially creating a gray area if the Task Group is not clear about what their relationship is with the O&S "parent" interest group.

**Comment by tucotuco** [comment] 2020-06-16 18:17
Thanks @pzermoglio and @baskaufs. I see what Paula is saying and it makes sense to me, particularly if/since ABCD could benefit from the work as well, and the two standards intend to work toward each other. I had the same concern about interaction with the DwC MG and hoped that something concreate could be in the TG charter about that. I fully support what Steve mentions about how to accomplish that.

**Comment by sophiathirza** [comment] 2020-08-17 07:28
The Task Group has been approved: https://www.tdwg.org/community/osr/how-did-it-die/. Many thanks for your help preparing the charter. 

We will have a working session at the TDWG 2020 virtual conference next month to begin work on the terms. It would be great if as many of you as possible could join us.

Thanks again, Sophie

**Comment by sophiathirza** [comment] 2020-09-17 10:15
Thanks @albenson-usgs. 

I've started an agenda for the working session: https://docs.google.com/document/d/1jvO6yMg0_PZq0KVWTJpk-358UYKkGqkPB-lw80v-3Xc. Once we've agreed the Task Group name we will set up a GitHub repository and we can report back from the session and continue the conversations there.  I'm really looking forward to the session.

**Comment by albenson-usgs** [comment] 2020-12-29 21:14
Curious what the status of the task group is? I didn't see a Github repo for it. Would like to watch the repo once it's up. Will someone report here when it is up?

**Comment by JohnNichollsTCD** [comment] 2020-12-29 22:18
Hi Abby - I've not heard anything from the group. I was not included in the meeting(s) and I am not even sure if nay progress has been made. Any repo would be much appreciated.

**Comment by sophiathirza** [comment] 2020-12-29 23:00
Hi Abby,
I asked for the Github repo to be set up after the working session but it's not been created yet. I'll ask again. Thanks for the reminder, Sophie

**Comment by sophiathirza** [comment] 2020-12-30 09:28
The GitHub repo has been set up for the Task Group: https://github.com/tdwg/how-did-it-die. I will copy all the information we have and the feedback from the working session into repo.

**Comment by sophiathirza** [comment] 2021-04-09 09:15
I have put all the information into the GitHub repository (https://github.com/tdwg/how-did-it-die) and it is now open for your contributions and discussions.

The repository is organised following the Collection Descriptions Interest Group (https://github.com/tdwg/cd) repository, hopefully it's clear but do suggest changes if you think something could be improved.

The proposed new properties (one to the core standard and four in a new extension) have separate issues to comment on the name, definition etc: https://github.com/tdwg/how-did-it-die/issues and I've created an issue for each new controlled vocabulary: https://github.com/tdwg/how-did-it-die/issues?q=is%3Aissue+is%3Aopen+label%3Avocabulary linked to a google document to add suggestions. The idea was to keep the vocabulary discussion separate from more general details of the property.

What we need now is:

   - agreement on the new properties (name, definition, whether core or extension)
   - suggestions for controlled vocabulary terms including definitions
   - uses cases to support the new properties and controlled vocabulary terms

Please add use cases as individual issues (https://github.com/tdwg/how-did-it-die/issues); I've added one for the roadkill term to get started: https://github.com/tdwg/how-did-it-die/labels/use%20case. I will move the use cases to the folder in the repository (https://github.com/tdwg/how-did-it-die/tree/main/use_cases) once we've agreed which use cases to include. There is some holding text in the folder for now.

I will arrange a meeting for early May to review the feedback and suggestions and decide how we can start writing it all up. Please let me know if you would like to join the call and what time zone you are in. We may need two calls.

I will write to all the attendees of the working session in TDWG 2020, apologies if you get this twice.

**Comment by albenson-usgs** [comment] 2021-04-09 12:35
I added a use case. I would like to be on the call if we can make it work given different time zones. My time zone is Mountain Daylight Time (GMT -6). Thanks Sophia for all your efforts on this!

**Comment by sophiathirza** [comment] 2021-06-04 17:23
We have a zoom call on 16th June at 18:00 CEST to discuss the feedback and suggestions from the GitHub repository (https://github.com/tdwg/how-did-it-die) and to decide how to proceed.

Let me me know if you would like to join. Thanks.

**Comment by JohnNichollsTCD** [comment] 2021-06-07 08:28
Dear Sophia

Unfortunately, I will not be able to attend on that date. I am still very interested in the developments of this group and I would be very happy to receive any updates that may arise from the meeting.

Best wishes

John


John Nicholls

Data Manager / Researcher
NorFish Project https://www.tcd.ie/history/research/centres/ceh/norfish/people.php
Centre for Environmental Humanities
6th floor, Arts and History Department
Trinity College Dublin
College Green, Dublin 2
Email: ***@***.******@***.***>
Phone: +3531896-1663

[cid:6908ccc8-dd49-480e-a7a6-3f256bccb8a6]

________________________________

**Comment by tucotuco** [comment] 2023-07-10 17:12
The new term dwc:vitality has been ratified and incorporated in the standard. Closing issue.

**Closed by tucotuco** 2023-07-10 17:12 UTC
Labels: Term - add, Class - Occurrence, Process - needs Task Group

**Comment by qgroom** [comment] 2024-09-13 04:07
For those of you interested in a causeOfDeath term I have added a specific term request here https://github.com/tdwg/dwc/issues/521
Please give it some support with comments and a :+1:
