### ISSUE TITLE
Something funky going on with the bookmarks/fragment identifiers on list of terms doc

### ISSUE THREAD

**Issue by baskaufs** [tdwg/dwc#291] opened 2020-10-21 17:20 UTC
When a DwC term redirects to the list of terms document, it initially jumps to the correct location in the document, but a split second later, it goes to a different location in the document. This is weird and not a behavior I have observed before. Since fragment identifiers are handled locally in the browser, it doesn't seem like it could be a server-side problem, but I can reproduce it both on Firefox and Chrome.

**Comment by tucotuco** [comment] 2020-12-25 20:34
@pzermoglio  could reproduce it in Chrome and Edge on Windows 10. It jumps to different places from one attempt to another.  It works for me in Chrome on MacOS, but has the same aberrant behavior in Safari.

**Comment by MattBlissett** [comment] 2021-01-05 15:34
I have noticed this for some time. Clicking/focussing the URL bar and pressing "Enter" usually moves to the correct place.

It's probably a similar cause as I found with the GBIF documents: some Javascript makes a legacy call of some sort, and resets the page position.

https://github.com/gbif/gbif-asciidoctor-toolkit/issues/7 -- it was MathJax in the documents.

**Comment by gkampmeier** [comment] 2021-04-20 19:38
I tried 4 different browsers (Brave, Chrome, Firefox, Safari, all updated) on the Mac OS (10.15.7) and none resolves properly, even after forcing a reload of the page. Not even close.

**Comment by peterdesmet** [comment] 2021-04-22 10:21
This issue is also described in #343 (for the `/terms`) page, with some more discussion. Closing this one here as a duplicate.

**Closed by peterdesmet** 2021-04-22 10:21 UTC
Labels: bug
