### ISSUE TITLE
Change term - relationshipOfResource

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc#194] opened 2018-08-29 22:30 UTC
## Change term

* Submitter: Peter Desmet @peterdesmet 
* Justification (why is this change necessary?): The definition is unclear, even misleading. The way it is, directionality of the relationship can be interpreted both ways. The relationship must be from subject to object.
* Proponents (who needs this change): Everyone who uses the term.

Current Term definition: https://dwc.tdwg.org/terms/#dwc:relationshipOfResource

Proposed new attributes of the term:

* Term name (in lowerCamelCase): relationshipOfResource
* Organized in Class (e.g. Location, Taxon): ResourceRelationship
* Definition of the term: **The relationship of the subject (identified by resourceID) to the object (identified by relatedResourceID).**
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.
* Examples: `sameAs`, `duplicate of`, `mother of`, `offspring of`, `sibling of`, **`parasite of`, `host of`**, `valid synonym of`, `located within`, **`pollinator of members of taxon`, `pollinated specific plant`, `pollinated by members of taxon`, `on slab with`**
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/relationshipOfResource-2018-09-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Associations/UnitAssociation/AssociationType

Original comment:
## The problem

The definition of [relationshipOfResource](http://rs.tdwg.org/dwc/terms/relationshipOfResource) is:

> The relationship of the resource identified by relatedResourceID to the subject (optionally identified by the resourceID). Recommended best practice is to use a controlled vocabulary.

But the intention was always to go from (@tucotuco concurs):

> resourceID (subject A) to relatedResourceID (object B)

Which is logical. The definition however goes in the other direction:

> The relationship of the resource identified by relatedResourceID (**B**) to the subject (**A**) (optionally identified by the resourceID). Recommended best practice is to use a controlled vocabulary.

That makes it very unintuitive, and the listed examples don't help (because e.g. `host to` could be interpreted in either direction). See for example how we struggled with it here: https://github.com/trias-project/uredinales-belgium-checklist/issues/8#issue-302633347:

> The resource relationship between rust fungi A and host B could be expressed as:
> 
> id | resourceID  | relatedResourceID | relationshipOfResource | relationshipAccordingTo
> --- | --- | --- | --- | ---
> A | (A) | B | host plant of | = bibliographicReference or source
> A | B | A | parasite of | = bibliographicReference or source
> 
> It is unfortunate that the most logical relationship is `host plant of`, which is less specific than `parasite of` but that is because the definition for relationshipOfResource.

## Updating the definition

Can we still amend the definition please? E.g to: 

> The relationship of the **subject (optionally identified by resourceID) to the object (identified by relatedResourceID)**. Recommended best practice is to use a controlled vocabulary.

## Breaking things

Obviously, people have probably done there best trying to understand the definition and been using it. Changing the direction of the relationship can break things. But:

- For describing relationships where the direction doesn't matter, nothing breaks (like `duplicate of`)
- How many datasets have been using the [Darwin Core Resource Relationship](http://rs.gbif.org/extension/dwc/resource_relation_2018_01_18.xml) (for directional relationships)? @mattblissett @timrobertson100 is there a way you can find out at GBIF / @pieterprovoost idem for OBIS?

I'd rather have this fixed now, assuming adoption is still low.

**Comment by peterdesmet** [comment] 2018-10-10 11:28
Any input on how to move this forward?

**Comment by MattBlissett** [comment] 2018-10-10 11:30
The setting for a custom domain on https://github.com/tdwg/dwc/settingshad disappeared, I don't know why.

**Comment by MattBlissett** [comment] 2018-10-10 11:34
https://github.com/tdwg/dwc/commit/856c3f38bcdd014b2829cb090010a3f6d3e1e354

I think changing the settings added this, so it should be OK now.

**Comment by tucotuco** [comment] 2018-10-10 12:14
Getting Internal Server Error for http://rs.tdwg.org/dwc

**Comment by tucotuco** [comment] 2020-09-05 17:24
I believe this to be a serious lingering problem. I think there is consensus that the correct way to make the relationships is as proposed. The change has definite semantic implications, so it can't just be done as an erratum despite what the original intention of the term definition was. We have three criteria that need to be satisfied for a term change to go forward. The first one is demand. We need to get multiple independent parties saying this change needs to be made. The second one the efficacy requirement. That should be easy to satisfy - the proposed change would actually make sense and be clearer than what we have now. The third one is the stability requirement, which is why we need to know what is already published, how the term was used in these cases, and whether those affected would be willing to make the adjustment once ratified. Maybe the first and third requirements can be solved with one set of communications.

We need someone to volunteer to take this forward.

**Comment by debpaul** [comment] 2020-09-07 15:38
I think this form is used at iDigBio when providers change identifiers. This has always confused me. Great to see (in a sense) that I was / am not alone. Quentin Groom nicely illustrated this in the paper on establishment means, etc. https://biss.pensoft.net/lib/ajax_srv/generate_pdf.php?document_id=38084&readonly_preview=1&file_id=0

I’m not at all sure how we will be able to a) locate all who are using the extension, or b) check to see if their current implementation is as intended or backwards.

For a), we need this in general — for many reasons. At any aggregator — we (users, data providers, developers), need an easy way to see / find all who are using extensions. The UI needs to show this plainly. You would then have easy access to who is using and how.

Sent from Shoe (my iPhone)

On Sep 5, 2020, at 1:24 PM, John Wieczorek <notifications@github.com> wrote:

﻿

I believe this to be a serious lingering problem. I think there is consensus that the correct way to make the relationships is as proposed. The change has definite semantic implications, so it can't just be done as an erratum despite what the original intention of the term definition was. We have three criteria that need to be satisfied for a term change to go forward. The first one is demand. We need to get multiple independent parties saying this change needs to be made. The second one the efficacy requirement. That should be easy to satisfy - the proposed change would actually make sense and be clearer than what we have now. The third one is the stability requirement, which is why we need to know what is already published, how the term was used in these cases, and whether those affected would be willing to make the adjustment once ratified. Maybe the first and third requirements can be solved with one set of communications.

We need someone to volunteer to take this forward.

**Comment by peterdesmet** [comment] 2020-09-07 18:25
I asked @timrobertson100 to give a breakdown of number GBIF-mediated datasets using the resourceRelationshipExtension per dataset type (occ/checklist) and publisher, so we have an idea of the current use.

**Comment by peterdesmet** [comment] 2020-09-07 18:28
Also, it would be great if this issue is tackled in the same swoop as #186.

**Comment by jhpoelen** [comment] 2020-09-23 16:09
To me, the proposed definition change is *not* semantically different. The original definition is just worded in a funny way. 

My attempt to parse the original definition:

> The relationship of the resource identified by relatedResourceID to the subject (optionally identified by the resourceID). Recommended best practice is to use a controlled vocabulary.

the object: relatedResourceID

the verb: the relationship

the (optional) subject: resourceID

to me the phrase ```identified by relatedResourceID to the subject``` indicates that the relatedResourceID is *not* the subject, but the thing that *relates* to the subject (i.e. the object).

So, as far as I can tell, the proposed updated definition makes the existing one more clear.

**Comment by jhpoelen** [comment] 2020-09-23 16:12
Also, please suggest to include the identifier for the relationship (or relationship id) see #186 in the example. 

For instance,  for ```parasite of``` add a relationship id [http://purl.obolibrary.org/obo/RO_0002444](http://purl.obolibrary.org/obo/RO_0002444) .

**Comment by jhpoelen** [comment] 2020-09-23 16:17
In addition, GloBI is indexing many collections that use the resource relationship extension. Also, I am aware that most EMu users (e.g., Field Museum, Smithsonian, Yale Peabody) are working with their vendor to put their relations into the resource relationship. If needed, I can provide more context, or perhaps Kate W. @magpiedin can chime in.

**Comment by magpiedin** [comment] 2020-09-23 19:12
👍 & agreed on the above/clarifying the definition

If usage-details from the Field Museum side help:  We're adding Resource Relationship extensions to a few of the FMNH IPT resources (e.g., [Insects dataset](https://fmipt.fieldmuseum.org/ipt/resource?r=fmnh_insects)).  Data-entry is shifting to [this interim workflow](https://docs.google.com/document/d/190msXiIYgui4zReB4O8-IQXq4Gue0GqQZU3wMCZG_jo/edit#heading=h.tc44y8ytraq5) (which lines up with @peterdesmet 's clarification above) while Axiell works on development. (& Axiell's been pretty responsive on accommodating this standard in EMu -- @fmjjones & @rondlg for details.)

As a side-note, a lot of the currently published relationships in FMNH data are also specimen-to-taxon, which might look odd without the 'scientificName' field to map to in our current IPT version's RR extension. (unless i missed a step? for now we included taxa in relationshipRemarks, formatted as "[other remarks] | scientificName: [taxon]")

**Comment by tucotuco** [comment] 2021-04-11 01:27
## Change term

* Submitter: Peter Desmet @peterdesmet 
* Justification (why is this change necessary?): The definition is unclear, even misleading. The way it is, directionality of the relationship can be interpreted both ways. The relationship must be from subject to object.
* Proponents (who needs this change): Everyone who uses the term.

Proposed new attributes of the term:

* Term name (in lowerCamelCase): relationshipOfResource
* Organized in Class (e.g. Location, Taxon): ResourceRelationship
* Definition of the term: The relationship of the subject (identified by resourceID) to the object (identified by relatedResourceID).
* Usage comments (recommendations regarding content, etc.): Recommended best practice is to use a controlled vocabulary.
* Examples: `sameAs`, `duplicate of`, `mother of`, `offspring of`, `parasite of`, `host of`, `sibling of`, `valid synonym of`, `located within`, `pollinator of members of taxon`, `pollinated specific plant`, `pollinated by members of taxon`
* Refines (identifier of the broader term this term refines, if applicable): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term, if applicable): http://rs.tdwg.org/dwc/terms/version/relationshipOfResource-2018-09-06
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG, if applicable): DataSets/DataSet/Units/Unit/Associations/UnitAssociation/AssociationType

**Comment by baskaufs** [comment] 2021-04-22 00:28
As noted in the comments for the `dwc:relationshipOfResourceID` proposal, the RDF guide did not attempt to model ResourceRelationship data, so no implications here for `dwciri:` terms.

**Comment by MattBlissett** [comment] 2021-04-22 10:49
> I asked @timrobertson100 to give a breakdown of number GBIF-mediated datasets using the resourceRelationshipExtension per dataset type (occ/checklist) and publisher, so we have an idea of the current use.

Part of this is now easy to answer, as the GBIF occurrence search index now includes information on available extensions.

https://www.gbif.org/occurrence/charts?advanced=1&dwca_extension=http:~2F~2Frs.tdwg.org~2Fdwc~2Fterms~2FResourceRelationship

```
curl -Ss 'https://api.gbif.org/v1/occurrence/search?dwca_extension=http://rs.tdwg.org/dwc/terms/ResourceRelationship&limit=0&facet=datasetKey&facetLimit=10000' | jq '.facets[].counts | length'
228 datasets

curl -Ss 'https://api.gbif.org/v1/occurrence/search?dwca_extension=http://rs.tdwg.org/dwc/terms/ResourceRelationship&limit=0&facet=publishingOrg&facetLimit=10000' | jq '.facets[].counts | length'
31 publishing organizations
```

The dataset type isn't recorded in the occurrence API, so:

```
for d in $(curl -Ss 'https://api.gbif.org/v1/occurrence/search?dwca_extension=http://rs.tdwg.org/dwc/terms/ResourceRelationship&limit=0&facet=datasetKey&facetLimit=10000' | jq -r '.facets[].counts[].name'); do curl -Ss https://api.gbif.org/v1/dataset/$d | jq -r '.type'; done | sort | uniq -c
    228 OCCURRENCE
```

These are all occurrence datasets.

**Comment by jhpoelen** [comment] 2021-05-28 15:13
@hollyel I am glad to see a pro-active stance from y'all paleo folks. @zedomel and Maarten Treekels (Meise Botanical Garden) are putting together a TDWG 2021 Symposium on Interactions (running title: ```eat or be eaten: don't miss out on interaction data```). I hope that you can with with them to share your use cases as examples during the symposium to facilitate discussion on how the paleo community can use the ResourceRelations extension. 

Question - would you consider paleo samples on same plate equivalent to saying that they co-occurred or were ecological related ? 


Also, if you already have specific examples of paleo interactions in existing collections (preferably your own), I'd be happy to help index these via GloBI to raise awareness. Right now, the only GloBI indexed paleo dataset that I am aware of is a dinosaur diet study that @KatjaSchulz transcribed from literature (see attached screenshots from https://www.globalbioticinteractions.org/?accordingTo=globi%3AKatjaSchulz%2Fdinosaur-biotic-interactions&interactionType=ecologicallyRelatedTo and https://www.globalbioticinteractions.org/browse?accordingTo=globi%3AKatjaSchulz%2Fdinosaur-biotic-interactions&interactionType=ecologicallyRelatedTo) 

Also see related change request #186 (older discussion), https://github.com/tdwg/dwc/issues/283 (formal proposal), and https://github.com/tdwg/interaction/issues/23 .

![Screenshot from 2021-05-28 08-10-36](https://user-images.githubusercontent.com/1084872/120005178-75589b80-bf8c-11eb-9acb-93875900741b.png)
![Screenshot from 2021-05-28 08-10-08](https://user-images.githubusercontent.com/1084872/120005181-75f13200-bf8c-11eb-84e1-5eda79c3fea3.png)

**Comment by hollyel** [comment] 2021-05-28 16:43
Thanks @jhpoelen. It would be great to discuss the application of the ResourceRelationship extension to paleo data in more detail. I’ll keep an eye out for that symposium. I can’t point to an existing documented example within the dataset I manage (NMNH Paleo - I don’t think we share much of if any of that data at the moment), but I will work on pulling examples that cover some of our primary use cases. For the most part I would say yes to your question. I’m sure there are some exceptions though. We sometimes use the term ‘community slab’ to refer to these types of specimens. There can of course be additional layers of interaction as well (fossil evidence of insect/plant interactions).

**Comment by tkarim** [comment] 2021-05-28 18:56
@jhpoelen getting at your question about fossil specimens associated on a slab... it depends. :) Sometimes you clearly have an ecological assemblage that was rapidly buried preserving an occurrence of a group of organisms (e.g. slabs of molting trilobites). You can usually identify this by the preservation and also the nature of the overlying sediments.  In other cases you have time averaged accumulations of individuals (that are often disarticulated), which can be identified again by the level of disarticulation and the nature of the sediment and the amount of reworking that is shown. Another important example here for fossils that hasn't been mentioned are lumps of amber that have multiple inclusions (e.g. you could have insects, plants, and air bubbles all in one piece of amber). The lumps are typically sliced up for imaging and/or other sampling, but the original ecological association of the various inclusions is very important to have recorded somewhere.

**Comment by EstebanMH-SiB** [comment] 2021-05-28 19:00
We endorse this proposal on behalf of @SiBColombia

**Comment by tkarim** [comment] 2021-05-28 19:01
@jhpoelen also... in response to your question about interactions... we have TONS in paleo collections that we are just starting to document. A lot of encrusters (e.g. bryozoans on bivalves), mollusks with bore holes, insect feeding traces on fossil plants, insect galls on fossil plants. This might make a good Paleo Data Happy Hour session for the fall.

**Comment by jhpoelen** [comment] 2021-05-28 19:50
@tkarim looking forward to seeing all the rich paleo interaction data (🦖 eats 🦕?) become easier to access. Please let me know how I can help and/or you have (prototype) examples of paleo records that recorded associations in existing DwC-A.

**Comment by tucotuco** [comment] 2021-06-02 20:29
> It would be helpful to include a paleo specific example (e.g., a relationship that defines fossil specimens preserved on the same slab) to encourage adoption of this extension by the paleo collections community. Our understanding is that changes to examples could be reviewed and added with relative ease after this review process. Assuming that is true, we would like to discuss within our working group and come up with a gold star example to add later. - Holly Little, Erica Krimmel (@ekrimmel) and Talia Karim (@tkarim) on behalf of the Paleo Data Working Group)

@hollyel @ekrimmel @tkarim 
If you come up with the example before the Maintenance Group makes the next release (work beginning on that now), we can include it without having to make a term change for this in the release after that. I anticipate that there is a window of about 30 days for this.

**Comment by hollyel** [comment] 2021-06-03 13:33
Thanks @tucotuco. We will work on an example and aim to get that to you in a couple of weeks. In addition to the example, additional vocabulary may need to be developed to cover the paleo use cases we are working on and to encourage consistent adoption. That will of course take time, but we want to evaluate some of that to ensure the example aligns with that ongoing vocabulary development.

**Comment by zedomel** [comment] 2021-06-16 15:03
@jhpoelen thanks for remembering the Biological Interaction Data symposium.

@hollyel, you are most welcome to join us, especially in the discussions in the Interest Group [https://github.com/tdwg/interaction](https://github.com/tdwg/interaction).

A paleo use case will be useful to validate the solution we are developing, so the paleo community can benefit from a common vocabulary for sharing **species interactions**.

**Comment by tucotuco** [comment] 2021-06-23 18:13
> Thanks @tucotuco. We will work on an example and aim to get that to you in a couple of weeks. In addition to the example, additional vocabulary may need to be developed to cover the paleo use cases we are working on and to encourage consistent adoption. That will of course take time, but we want to evaluate some of that to ensure the example aligns with that ongoing vocabulary development.

@hollyel Do you have the additional example? We are otherwise ready to move forward on ratifying the terms from the latest public review.

**Comment by hollyel** [comment] 2021-06-23 18:39
@tucotuco Yes! Apologies for the delay. We have reviewed with the Paleo Data Working Group and propose including "on slab with" in the example list. An example of this relationship: "[a1be8a3c-090f-11e3-af8d-50faf7e7a06b](https://www.gbif.org/occurrence/607667809) on slab with [a1beaa2a-090f-11e3-af8d-50faf7e7a06b](https://www.gbif.org/occurrence/607667810)". I included the links for easy access to the records and the associated images.

**Comment by tucotuco** [comment] 2021-06-23 18:49
Incorporated, thanks.

**Comment by gdadade** [comment] 2021-06-24 09:06
This term is used in GGBN regularly and we agreed on a vocabulary within GGBN, but I think we need to review it to ensure it can be used in a broader context. Currently we use e.g. "same individual", "same population" since the voucher can be either the same organism as the tissue or just from the same population. I hope we can add examples from our community for broader usage in the near future.

**Comment by deepreef** [comment] 2021-06-26 18:07
> Currently we use e.g. "same individual", "same population" since the voucher can be either the same organism as the tissue or just from the same population.

Note that an instance of `Organism` can represent either a single individual organism, or an entire population of organisms.  I'm not sure if that addresses the issue you raise, but because the scope of an instance of `Organism` can be scaled up to (and beyond) a population (as long as it's taxonomically homogeneous), then it seems like there should be a away to accommodate both "same individual" and "same population" using appropriately-scaled instances of `Organism`.

**Comment by tucotuco** [comment] 2021-08-25 03:11
Done.

**Comment by ekrimmel** [comment] 2021-11-03 00:05
@tucotuco I notice that the example phrase "on slab with" didn't make it into the official term documentation (looking [here](https://dwc.tdwg.org/list/#dwc_relationshipOfResource)), perhaps because we provided it last minute to you. Is it possible to get that included now, given that it is included in this issue and this issue has been reviewed and passed? Thanks!

@hollyel @tkarim

**Comment by tucotuco** [comment] 2021-11-03 14:34
Neglected example added in new Issue #400. Closing this issue.

**Closed by tucotuco** 2021-11-03 14:34 UTC
Labels: Term - change, Class - ResourceRelationship, non-normative, Process - complete
